// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBsXF5Z6Tdh9OARv1U-pZd-f1qzpnQtFbs',
    appId: '1:837580173613:web:74ee4b535c4292d671e3a4',
    messagingSenderId: '837580173613',
    projectId: 'edspert-a3faa',
    authDomain: 'edspert-a3faa.firebaseapp.com',
    storageBucket: 'edspert-a3faa.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC2vgvDTFf_aT_ivoXT3FLacowMLW_NUXo',
    appId: '1:837580173613:android:b11fb33ed76ea7dc71e3a4',
    messagingSenderId: '837580173613',
    projectId: 'edspert-a3faa',
    storageBucket: 'edspert-a3faa.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAESAC5zedeaRZb7EcIMm7BjIx7OOeYa8w',
    appId: '1:837580173613:ios:4960bd87cfb6913371e3a4',
    messagingSenderId: '837580173613',
    projectId: 'edspert-a3faa',
    storageBucket: 'edspert-a3faa.appspot.com',
    iosClientId: '837580173613-sp7easllkbfcsnkjs65acnnsdns4o0ms.apps.googleusercontent.com',
    iosBundleId: 'com.example.learning',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAESAC5zedeaRZb7EcIMm7BjIx7OOeYa8w',
    appId: '1:837580173613:ios:1ed40564ada1cce071e3a4',
    messagingSenderId: '837580173613',
    projectId: 'edspert-a3faa',
    storageBucket: 'edspert-a3faa.appspot.com',
    iosClientId: '837580173613-lur09meeo9q7hj9m3q2tq2rpldvjnqq1.apps.googleusercontent.com',
    iosBundleId: 'com.example.learning.RunnerTests',
  );
}
